# Builds engine/build/doom-term. Run from repo root: make -C engine
DG      := doomgeneric/doomgeneric
OUT     := build/doom-term
CC      ?= gcc
CFLAGS  += -O2 -Wall -Wno-unused-result -DNORMALUNIX -DLINUX -DSNDSERV -D_DEFAULT_SOURCE \
           -DDOOMGENERIC_RESX=320 -DDOOMGENERIC_RESY=200 -I$(DG)
LIBS    += -lm -lpthread

SRC_DOOM = dummy am_map doomdef doomstat dstrings d_event d_items d_iwad d_loop d_main d_mode d_net \
  f_finale f_wipe g_game hu_lib hu_stuff info i_cdmus i_endoom i_joystick i_scale i_sound i_system \
  i_timer memio m_argv m_bbox m_cheat m_config m_controls m_fixed m_menu m_misc m_random p_ceilng \
  p_doors p_enemy p_floor p_inter p_lights p_map p_maputl p_mobj p_plats p_pspr p_saveg p_setup \
  p_sight p_spec p_switch p_telept p_tick p_user r_bsp r_data r_draw r_main r_plane r_segs r_sky \
  r_things sha1 sounds statdump st_lib st_stuff s_sound tables v_video wi_stuff w_checksum w_file \
  w_main w_wad z_zone w_file_stdc i_input i_video doomgeneric

OBJS := $(addprefix build/, $(addsuffix .o, $(SRC_DOOM))) build/doomgeneric_term.o

all: deps $(OUT)

deps:
	@[ -f $(DG)/doomgeneric.h ] && [ -f wads/freedoom1.wad -o -f wads/doom1.wad ] || ./get-deps.sh

$(OUT): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $@ $(LIBS)

build/%.o: $(DG)/%.c | build
	@$(CC) $(CFLAGS) -c $< -o $@

build/doomgeneric_term.o: src/doomgeneric_term.c | build
	$(CC) $(CFLAGS) -c $< -o $@

build:
	mkdir -p build

clean:
	rm -rf build

.PHONY: all deps clean
